### ISSUE TITLE
github test case failing with cookie key error

### ISSUE THREAD

**Issue by hcarter333** [hcarter333/datasette-enrichments-gmap-geocode#5]
It appears the error is:

```
tests/test_datasette_enrichments_gmap_geocode.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Cookies[]>, name = 'ds_csrftoken'

    def __getitem__(self, name: str) -> str:
        value = self.get(name)
        if value is None:
>           raise KeyError(name)
E           KeyError: 'ds_csrftoken'

/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_models.py:1148: KeyError
=========================== short test summary info ============================
FAILED tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[True-True] - KeyError: 'ds_csrftoken'

```

I'm guessing the prepended ds is for datasette. It works on a local machine, so the question seems to be, "What different about ds_csrftoken on the github machine?

Also! The test rig doesn't do a datasette install, so I'll try that next.

**Comment by hcarter333** [comment]
The install was easy to try, but didn't help. I've taken it abck out.

I found [documentation](datasette install datasette-enrichments-gmap-geocode) on how Datasette uses these tokens.

In that documentation, there is no prepending ds_. I'll try tro remove it locally, see if I get a pass, and then try it in the github repository.

Thsi combination:
```
    csrftoken = (
        await datasette.client.get("/-/enrich/data/addresses/gm_api_geocoder", cookies=cookies)
    ).cookies["csrftoken"]
    cookies["ds_csrftoken"] = csrftoken

```
resulted in  this error:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Cookies[<Cookie ds_csrftoken=ImphczFVWXhldmlhR0pPNGgi.BXq9McKUYOozYnZTczR0fhWzIRQ for localhost.local />]>, name = 'csrftoken'

    def __getitem__(self, name: str) -> str:
        value = self.get(name)
        if value is None:
>           raise KeyError(name)
E           KeyError: 'csrftoken'

../.local/lib/python3.9/site-packages/httpx/_models.py:1153: KeyError

```
indicating that the non-ds_ key just isn't returned from the object when run locally.

I'll try that in github to see if there's a difference.

**Comment by hcarter333** [comment]
Got the same error on github. It's not the name of the key, that's causing the issue. Neither of the key names exists.  

That leads me to wonder if it's the call to get not succeeding that's resulting in their being no cookies structure. I'll try that experiment next.

**Comment by hcarter333** [comment]
I'm using this locally to be able to view the conents of the 'get' methods return value

```
    csget = (
        await datasette.client.get("/-/enrich/data/addresses/gm_api_geocoder", cookies=cookies)
    )
    print(str(csget.cookies))
    cookies["ds_csrftoken"] = csget.cookies["ds_csrftoken"]

```
Trying the same code remotely on github gives

The dictionary prints as empty.

```
----------------------------- Captured stdout call -----------------------------
<Cookies[]>
========================= 4 failed, 4 errors in 1.21s ==========================

```
Also note, that on the local version there's mention of local.localhost. Is that not allowed on github?

I found [this](https://stackoverflow.com/questions/68691293/localhost-can-not-be-accessed-on-github-actions-workflow)

I'm trying the change to 127.0.0.1

That resulted in a timeout

```
E       httpx.TimeoutException: No response can be found for GET request on http://localhost/-/enrich/data/addresses/gm_api_geocoder amongst:
E       Match GET requests on re.compile('https://maps.googleapis.com/maps/api/geocode/json.*')

/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_httpx/_httpx_mock.py:211: TimeoutException

```

I'm going to print the resonse code next back on localhost

And sure enough!
```
E           KeyError: 'ds_csrftoken'

/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/httpx/_models.py:1154: KeyError
----------------------------- Captured stdout call -----------------------------
<Response [404 Not Found]>
<Cookies[]>
========================= 4 failed, 4 errors in 0.76s ==========================
Error: Process completed with exit code 1.

```

**Comment by hcarter333** [comment]
Trying localhost:8001 resulted in the same error remotely, using localhost.local resulted in a timeout. Both worked fine on my local machine.

**Comment by hcarter333** [comment]
Noticed that the opencage action output was one version of datasette back, so tried that. Still failing as shown above.

```
Collecting datasette<0.64.6 (from datasette-enrichments-gmap-geocode==0.1)
  Downloading datasette-0.64.5-py3-none-any.whl.metadata (7.7 kB)

```

Also! I get the exact same errors running pytest in a codespace both for this project and for opencage

![image](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/363004/1650f67b-b496-4d87-b05c-79c59fecc498)

**Comment by simonw** [comment]
I was able to replicate this problem on my laptop by installing everything in a fresh virtual environment like this:
```bash
cd /tmp
git clone https://github.com/hcarter333/datasette-enrichments-gmap-geocode
cd datasette-enrichments-gmap-geocode
python -m venv venv
source venv/bin/activate
pip install -e '.[test]'
pytest
```
This gave me the same errors as GitHub:
```
============================================================== short test summary info ==============================================================
FAILED tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[True-True] - KeyError: 'ds_csrftoken'
FAILED tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[True-False] - KeyError: 'ds_csrftoken'
FAILED tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[False-True] - KeyError: 'ds_csrftoken'
FAILED tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[False-False] - KeyError: 'ds_csrftoken'
ERROR tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[True-True] - AssertionError: The following responses are mocked but not requested:
ERROR tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[True-False] - AssertionError: The following responses are mocked but not requested:
ERROR tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[False-True] - AssertionError: The following responses are mocked but not requested:
ERROR tests/test_datasette_enrichments_gmap_geocode.py::test_enrichment[False-False] - AssertionError: The following responses are mocked but not requested:
====================================================== 4 failed, 7 warnings, 4 errors in 2.93s ======================================================
```

**Comment by simonw** [comment]
I used the `pytest` debugger to investigate:
```bash
pytest -x --pdb
```
The `-x` means stop at the first error, and `--pdb` drops me into a debugger at that error.

It looks like the core problem is actually this 404 error:

![pdb](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/9599/384d434e-95a7-4b37-909a-798cbb2e07b1)

**Comment by simonw** [comment]
I manually tested the enrichment locally and it worked perfectly:

![CleanShot 2023-12-29 at 10 20 29@2x](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/9599/7eeda6e0-922e-4278-a047-638be5f8ad9c)

**Comment by simonw** [comment]
Something I noticed in the debugger:

```
datasette._plugins()
```
```json
[
    {
        "name": "datasette-enrichments",
        "static": false,
        "templates": true,
        "version": "0.2",
        "hooks": []
    },
    {
        "name": "datasette-enrichments-gmap-geocode",
        "static": false,
        "templates": false,
        "version": "0.1",
        "hooks": []
    }
]
```
But... if you visit `/-/plugins` while running Datasette you get this:
```json
[
    {
        "name": "datasette-enrichments",
        "static": false,
        "templates": true,
        "version": "0.2",
        "hooks": [
            "actor_from_request",
            "permission_allowed",
            "register_routes",
            "table_actions"
        ]
    },
    {
        "name": "datasette-enrichments-gmap-geocode",
        "static": false,
        "templates": false,
        "version": "0.1",
        "hooks": [
            "register_enrichments"
        ]
    }
]
```
For some reason the `hooks` arrays are empty when running inside of `pytest` - that seems like an important clue to me.

**Comment by simonw** [comment]
I confirmed that for my other enrichments projects with tests that pass the `"hooks"` arrays are correctly populated when running under `pytest`.

**Comment by simonw** [comment]
I ran a diff against the `pyproject.toml` from this plugin compared to the OpenCage one, but the differences don't look like they could explain this bug: https://gist.github.com/simonw/08fccb783a4e1c8e2074ee402b8b1daa/revisions

**Comment by simonw** [comment]
Here's a similar diff for the tests themselves: https://gist.github.com/simonw/6925a3f24ad5ba85b92c8ec911eabeab/revisions

I can't see any differences that might explain what's happening here.

One thought:

`await datasette.client.get("/-/enrich/data/addresses/opencage", cookies=cookies)` works.

`await datasette.client.get("/-/enrich/data/addresses/gm_api_geocoder", cookies=cookies)` 404s

Could it be the underscores in the name of the enrichment?

That seems really unlikely though, since that should also break the manual testing which works fine.

**Comment by simonw** [comment]
No, that's not it - I tried renaming to `gmapigeocoder`:

```diff
diff --git a/datasette_enrichments_gmap_geocode/__init__.py b/datasette_enrichments_gmap_geocode/__init__.py
index 042ae68..a7402d4 100644
--- a/datasette_enrichments_gmap_geocode/__init__.py
+++ b/datasette_enrichments_gmap_geocode/__init__.py
@@ -24,7 +24,7 @@ def register_enrichments(datasette):
 
 class GmapGeocodeEnrichment(Enrichment):
     name = "Google Maps API geocoder"
-    slug = "gm_api_geocoder"
+    slug = "gmapigeocoder"
     description = "Geocode to latitude/longitude points using Google Mapss API geocoder"
     batch_size = 1
     log_traceback = True
diff --git a/tests/test_datasette_enrichments_gmap_geocode.py b/tests/test_datasette_enrichments_gmap_geocode.py
index 779ec19..0f79ebf 100644
--- a/tests/test_datasette_enrichments_gmap_geocode.py
+++ b/tests/test_datasette_enrichments_gmap_geocode.py
@@ -46,14 +46,14 @@ async def test_enrichment(tmpdir, api_key_from_config, store_json_column, httpx_
 
     cookies = {"ds_actor": datasette.sign({"a": {"id": "root"}}, "actor")}
     csget = (
-        await datasette.client.get("/-/enrich/data/addresses/gm_api_geocoder", cookies=cookies)
+        await datasette.client.get("/-/enrich/data/addresses/gmapigeocoder", cookies=cookies)
     )
     print(str(datasette))
     print(str(csget))
     print(str(csget.cookies))
     cookies["ds_csrftoken"] = csget.cookies["ds_csrftoken"]
 #    csrftoken = (
-#        await datasette.client.get("/-/enrich/data/addresses/gm_api_geocoder", cookies=cookies)
+#        await datasette.client.get("/-/enrich/data/addresses/gmapigeocoder", cookies=cookies)
 #    ).cookies["csrftoken"]
 #    cookies["ds_csrftoken"] = csrftoken
 #    print("cookies is " + str(cookies))
@@ -67,7 +67,7 @@ async def test_enrichment(tmpdir, api_key_from_config, store_json_column, httpx_
     if store_json_column:
         post["json_column"] = "details"
     response = await datasette.client.post(
-        "/-/enrich/data/addresses/gm_api_geocoder",
+        "/-/enrich/data/addresses/gmapigeocoder",
         data=post,
         cookies=cookies,
     )
```
But the tests fail the same way.

**Comment by simonw** [comment]
New guess: maybe the `addresses` table can't be seen by Datasette when running the tests? Potentially a timing issue where the table has not been created in the SQLite database by the time the test tries to access that `/-/enrich/data/addresses/...` page?

That should show up in other plugins that use the same testing pattern, but it's still worth investigating as an option.

**Comment by simonw** [comment]
Ruled that out with:
```diff
diff --git a/tests/test_datasette_enrichments_gmap_geocode.py b/tests/test_datasette_enrichments_gmap_geocode.py
index 779ec19..0f2838a 100644
--- a/tests/test_datasette_enrichments_gmap_geocode.py
+++ b/tests/test_datasette_enrichments_gmap_geocode.py
@@ -44,6 +44,9 @@ async def test_enrichment(tmpdir, api_key_from_config, store_json_column, httpx_
         metadata["plugins"] = {"datasette-enrichments-gmap-geocode": {"api_key": "abc123"}}
     datasette = Datasette([db_path], metadata=metadata)
 
+    table_names = await datasette.get_database("data").table_names()
+    assert "addresses" in table_names
+
     cookies = {"ds_actor": datasette.sign({"a": {"id": "root"}}, "actor")}
     csget = (
         await datasette.client.get("/-/enrich/data/addresses/gm_api_geocoder", cookies=cookies)
```

**Comment by simonw** [comment]
The enrichment is not being registered!

I added this code:
```diff
diff --git a/tests/test_datasette_enrichments_gmap_geocode.py b/tests/test_datasette_enrichments_gmap_geocode.py
index 779ec19..674871e 100644
--- a/tests/test_datasette_enrichments_gmap_geocode.py
+++ b/tests/test_datasette_enrichments_gmap_geocode.py
@@ -44,6 +44,9 @@ async def test_enrichment(tmpdir, api_key_from_config, store_json_column, httpx_
         metadata["plugins"] = {"datasette-enrichments-gmap-geocode": {"api_key": "abc123"}}
     datasette = Datasette([db_path], metadata=metadata)
 
+    from datasette_enrichments import get_enrichments
+    enrichments = await get_enrichments(datasette)
+
     cookies = {"ds_actor": datasette.sign({"a": {"id": "root"}}, "actor")}
     csget = (
         await datasette.client.get("/-/enrich/data/addresses/gm_api_geocoder", cookies=cookies)
```
And now in the debugger I see this:
```
-> cookies["ds_csrftoken"] = csget.cookies["ds_csrftoken"]
(Pdb) enrichments
{}
```

**Comment by simonw** [comment]
Here's the relevant code in `datasette-enrichments` itself: https://github.com/datasette/datasette-enrichments/blob/eeded4173fff0614e2efe559022a9023e5ff8640/datasette_enrichments/__init__.py#L27-L32

We're clearly dealing with some kind of weird Pluggy problem here.

I wonder if it's related to the fact that the `datasette-enrichments` plugin itself exposes plugin hooks used by another plugin. This pattern: https://til.simonwillison.net/datasette/register-new-plugin-hooks

**Comment by simonw** [comment]
Open questions:
- How come this works when running within Datasette but fails inside the tests?
- Why do the almost-identical tests for `datasette-enrichments-opencage` work when the tests for `datasette-enrichments-gmap-geocode` fail?
- Related: how come this issue hasn't come up before for some other plugin?
- Is the way `datasette-enrichments` adds a new plugin hook flawed in some way?

**Comment by hcarter333** [comment]
Running on a github codespace, I get similar, but not identical results:

![image](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/363004/a9222447-0a4d-42bb-8af2-d86bf602a02c)

The line numbers for the errors are slightly different, but I'm guessing that's a result of the debug experiments you tried @simonw .

I believe this is a link to the codespace I'm using on opencage:
https://vscode.dev/profile/github/8a06a64a78fdfaa9b1d0a6de8b4ba4bd

**Comment by hcarter333** [comment]
Locally, both datasette-enrichments-opencage 

![image](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/363004/6b4132a6-845f-4793-9226-cc1c8bbfb2ad)

and datasette-enrichments-gmap-geocode

![image](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/363004/ea3c67f4-3ee8-4b41-a55c-b31f3d2ffbc8)

pass.

**Comment by simonw** [comment]
Aha! It turns out installing `datasette-enrichments-opencage` in the same virtual environment as everything else causes the tests to pass!

Now I need to figure out why.

**Comment by simonw** [comment]
This means you could temporarily fix your GitHub Actions tests here by adding this line to `pyproject.toml`:

```toml
[project.optional-dependencies]
test = ["pytest", "pytest-asyncio", "pytest-httpx", "datasette-enrichments-opencage"]
```
That's a workaround, but I'm not satisfied personally until I figure out how to not need to do that.

**Comment by hcarter333** [comment]
Cool :)
That's interesting! I'll give it a try.

**Comment by hcarter333** [comment]
That did the trick.
![image](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/363004/e1a7066f-f92f-41dd-8f9a-dfcded9d6a27)

Which, I guess, begs the question, what is `datasette-enrichments-opencage` bringing in that wasnt in this enrichment? I'm looking into it as well.

**Comment by hcarter333** [comment]
I released the enrichment. Still debugging this issue.
![image](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/363004/40952fd7-aa47-44d3-b79a-af50e462eb45)

**Comment by hcarter333** [comment]
Given that an pytest_asycnio version number was the fix for #7 I'm wondering if the opencage dependency makes datasette take the bit more time to initialize that avoids a race condition that's happening here. That then leaves the question of why opencage passed, but that was two months ago. I'm off to compare installed dependencies from the opencage run on 3.8 in the [gist](https://gist.github.com/hcarter333/94ed823cb09d5c24453a17f8d046e666/revisions) from #7.

**Comment by hcarter333** [comment]
The immediately obvious difference is this

Run pip install -e '.[test]'	Run pip install '.[test]'

I removed the -e from the gmap version and the test cases still passed. The next step will be to try to remove the opencage dependency again.

**Comment by hcarter333** [comment]
Revmoving the dependency resulted in test case failures with the 404 signature. Looking for more differences.

**Comment by hcarter333** [comment]
There are a number of version differences. I'm going to focus on asyncio first.
![image](https://github.com/hcarter333/datasette-enrichments-gmap-geocode/assets/363004/a85c89f2-3ec4-441d-9b2c-05c76d24881e)

**Comment by hcarter333** [comment]
And that fixed it! No need to have a datasette-opencage dependency at this point. 

@simonw I'll close this for now, but I'd be happy to re-open it if it's the place that the pytest-asyncio issue should be followed to root cause.

**Comment by simonw** [comment]
Well spotted! I had to downgrade that in another project yesterday too.
